/**
 * Controla a documentação HTML, alternando idioma, navegação interna e busca local de conteúdo.
 * Créditos do projeto: Nostrand.
 */

const translations = {
  "pt-BR": {
    meta: {
      title: "Documentação do Gutenberg",
      brandSubtitle: "Documentação oficial do projeto",
      searchPlaceholder: "Buscar na documentação...",
      heroEyebrow: "Documentação",
      heroTitle: "Como usar o Gutenberg para criar livros, roteiros e ler EPUBs e PDFs",
      heroDescription: `Esta documentação descreve o funcionamento do aplicativo <strong>Gutenberg</strong>, cobrindo a criação de projetos, edição de capítulos, escrita de roteiros, revisão, exportação e o uso da biblioteca integrada para leitura.`,
      footerText: "Documentação do projeto Gutenberg.",
      menuLabel: "Abrir menu"
    },
    nav: [
      ["visao-geral", "Visão geral"], ["recursos", "Recursos principais"], ["instalacao", "Instalação e execução"], ["estrutura", "Estrutura do projeto"], ["fluxo-livros", "Fluxo de trabalho para livros"], ["criar-livro", "Criando um projeto de livro"], ["editor-livro", "Editor de livro"], ["revisao", "Revisão ortográfica"], ["estatisticas-livro", "Estatísticas do projeto"], ["exportacao-livro", "Exportação de livros"], ["importacao-documentos", "Importação de documentos"], ["arquivos-gut", "Arquivos .gut"], ["fluxo-roteiros", "Fluxo de trabalho para roteiros"], ["criar-roteiro", "Criando um projeto de roteiro"], ["editor-roteiro", "Editor de roteiro"], ["blocos-roteiro", "Blocos de roteiro"], ["catalogo", "Catálogo de personagens e locais"], ["estatisticas-roteiro", "Estatísticas do roteiro"], ["exportacao-roteiro", "Exportação de roteiros"], ["biblioteca", "Biblioteca EPUB e PDF"], ["ler-epub-pdf", "Como ler EPUBs e PDFs"], ["configuracoes", "Configurações"], ["atalhos", "Atalhos e comandos"], ["armazenamento", "Arquivos gerados e armazenamento"], ["solucao-problemas", "Solução de problemas"], ["boas-praticas", "Boas práticas"]
    ],
    sections: {
      "visao-geral": `<section class="callout info" id="visao-geral"><h2>Visão geral</h2><p>O Gutenberg é um aplicativo desktop/web voltado para <strong>criação literária</strong> e <strong>organização de leitura</strong>. Ele permite criar projetos de <strong>livro</strong> e <strong>roteiro</strong>, editar conteúdo com salvamento automático, revisar texto, exportar em formatos como EPUB, DOCX e PDF, além de manter uma biblioteca própria para leitura de arquivos <strong>.epub</strong> e <strong>.pdf</strong>.</p><p>A interface foi construída com <strong>Flask + HTML + CSS + JavaScript</strong>, e o aplicativo também pode ser executado como programa desktop com <strong>pywebview</strong>.</p></section>`,
      "recursos": `<section id="recursos"><h2>Recursos principais</h2><div class="card-grid two"><article class="card"><h3>Criação de projetos</h3><p>Suporte a dois tipos de projeto: <strong>Livro</strong> e <strong>Roteiro</strong>.</p></article><article class="card"><h3>Editor de livro</h3><p>Edição por capítulo com formatação rica, imagens, títulos, listas e salvamento automático.</p></article><article class="card"><h3>Editor de roteiro</h3><p>Blocos específicos para cena, ação, personagem, diálogo, transição, comentário, música e mais.</p></article><article class="card"><h3>Revisão de texto</h3><p>Integração com Gemini para revisar ortografia, gramática, pontuação e pequenos ajustes de redação.</p></article><article class="card"><h3>Exportação</h3><p>Livros: EPUB 2.0, EPUB 3.0, XHTML, DOCX e PDF. Roteiros: DOCX e PDF.</p></article><article class="card"><h3>Importação</h3><p>Projetos aceitam importação de <strong>.gut</strong>, <strong>.docx</strong>, <strong>.pdf</strong> e <strong>.txt</strong>, com conversão para capítulos ou roteiros conforme o tipo do projeto.</p></article><article class="card"><h3>Snapshots .gut</h3><p>Capítulos de livros e roteiros podem ser salvos em um pacote <strong>.gut</strong> para backup, transferência e restauração em projetos compatíveis.</p></article><article class="card"><h3>Biblioteca</h3><p>Leitura de EPUB e PDF com progresso, capítulos, sumário, marcação de leitura e coleções automáticas.</p></article></div></section>`,
      "instalacao": `<section id="instalacao"><h2>Instalação e execução</h2><h3>Instalar dependências</h3><pre><code>pip install -r requirements.txt</code></pre><h3>Executar no navegador</h3><pre><code>python server_only.py</code></pre><p>Depois, abra o endereço:</p><pre><code>http://127.0.0.1:5000</code></pre><h3>Executar como aplicativo desktop</h3><pre><code>python app.py</code></pre><h3>Gerar executável com PyInstaller</h3><pre><code>pyinstaller Gutenberg.spec</code></pre><p>O executável será gerado em <code>dist/Gutenberg/</code>.</p></section>`,
      "estrutura": `<section id="estrutura"><h2>Estrutura do projeto</h2><pre><code>raiz_do_projeto/
├── app.py
├── server_only.py
├── modules/
├── static/
├── templates/
├── appdata/
├── locales/
├── requirements.txt
├── Gutenberg.spec
└── README.md</code></pre><div class="table-wrap"><table><thead><tr><th>Pasta / arquivo</th><th>Função</th></tr></thead><tbody><tr><td><code>app.py</code></td><td>Inicializa o aplicativo desktop com pywebview.</td></tr><tr><td><code>server_only.py</code></td><td>Executa apenas o servidor Flask.</td></tr><tr><td><code>modules/</code></td><td>Lógica de backend: projetos, capítulos, roteiros, biblioteca, exportação e revisão.</td></tr><tr><td><code>templates/</code></td><td>Páginas HTML renderizadas pelo Flask.</td></tr><tr><td><code>static/</code></td><td>Arquivos CSS, JavaScript e imagens da interface.</td></tr><tr><td><code>locales/</code></td><td>Traduções da interface em português e inglês.</td></tr><tr><td><code>appdata/config.json</code></td><td>Configurações globais do aplicativo.</td></tr><tr><td><code>appdata/progress.json</code></td><td>Informações relacionadas a progresso e estado local.</td></tr></tbody></table></div></section>`,
      "fluxo-livros": `<section id="fluxo-livros"><h2>Fluxo de trabalho para livros</h2><ol class="steps"><li>Criar um novo projeto do tipo <strong>Livro</strong>.</li><li>Definir título, descrição, autor, idioma, tags e, se quiser, uma capa.</li><li>Criar capítulos individualmente.</li><li>Editar o conteúdo de cada capítulo no editor.</li><li>Usar a revisão ortográfica quando necessário.</li><li>Ler o capítulo no modo leitura.</li><li>Exportar o projeto em EPUB, XHTML, DOCX ou PDF.</li></ol></section>`,
      "criar-livro": `<section id="criar-livro"><h2>Criando um projeto de livro</h2><p>Na tela inicial, clique em <strong>Novo projeto</strong>. No formulário de criação, selecione o tipo <strong>Livro</strong>.</p><h3>Campos do formulário</h3><div class="table-wrap"><table><thead><tr><th>Campo</th><th>Descrição</th></tr></thead><tbody><tr><td>Título</td><td>Nome principal do projeto. É obrigatório.</td></tr><tr><td>Descrição</td><td>Resumo do livro ou observações gerais.</td></tr><tr><td>Autor</td><td>Nome do autor.</td></tr><tr><td>Idioma</td><td>Idioma principal do projeto. Afeta revisão e identificação.</td></tr><tr><td>Tags</td><td>Palavras-chave separadas por vírgula.</td></tr><tr><td>Capa</td><td>Imagem opcional usada no projeto e na exportação.</td></tr></tbody></table></div><div class="callout tip"><strong>Dica:</strong> use tags para organizar gêneros, temas ou séries. Isso facilita sua identificação futura no painel inicial.</div></section>`,
      "editor-livro": `<section id="editor-livro"><h2>Editor de livro</h2><p>Cada capítulo é editado em uma tela própria. O editor salva automaticamente o conteúdo e permite escrever com formatação rica.</p><h3>Ferramentas disponíveis</h3><div class="card-grid two"><article class="card"><h4>Alinhamento</h4><p>À esquerda, centralizado, à direita e justificado.</p></article><article class="card"><h4>Recuo</h4><p>Remover recuo ou aumentar recuo do parágrafo.</p></article><article class="card"><h4>Estilo</h4><p>Negrito, itálico e sublinhado.</p></article><article class="card"><h4>Estrutura</h4><p>Parágrafo, H1, H2, H3 e lista não ordenada.</p></article><article class="card"><h4>Elementos visuais</h4><p>Linha horizontal, separador decorativo e delimitador decorativo.</p></article><article class="card"><h4>Recursos extras</h4><p>Inserção de imagem, troca de família tipográfica e limpeza de formatação.</p></article></div><h3>Salvamento automático</h3><p>O editor utiliza um sistema de <strong>autosave</strong>. Isso significa que o conteúdo do capítulo e o título são enviados automaticamente ao backend durante o uso. Na prática, você não precisa clicar em um botão de salvar a cada alteração.</p><h3>Modo leitura</h3><p>Dentro do editor existe um botão de <strong>Modo leitura</strong>. Ele abre o capítulo em uma visualização voltada para leitura, com preferências como tema, fonte, tamanho da fonte e largura de leitura.</p></section>`,
      "revisao": `<section id="revisao"><h2>Revisão ortográfica</h2><p>O editor de livro e o editor de roteiro possuem uma função de revisão baseada no Gemini. O texto é processado em blocos, preservando a estrutura original e propondo correções de ortografia, pontuação, concordância e pequenos ajustes gramaticais.</p><h3>Como usar</h3><ol class="steps compact"><li>Abra o editor.</li><li>Clique no botão <strong>Revisar</strong>.</li><li>O sistema prepara os blocos do texto para análise.</li><li>Compare o texto atual com a sugestão corrigida.</li><li>Escolha entre ignorar o bloco, revisar novamente ou aceitar a revisão.</li></ol><h3>Pré-requisito</h3><p>Para a revisão funcionar, é necessário definir a <strong>chave da API do Google Gemini</strong> em <strong>Configurações</strong>. Sem essa chave, o recurso não conseguirá consultar o serviço externo.</p></section>`,
      "estatisticas-livro": `<section id="estatisticas-livro"><h2>Estatísticas do projeto</h2><p>Projetos de livro possuem uma área de <strong>estatísticas</strong>, acessível na tela do projeto. Ela foi pensada para acompanhar o tamanho e o comportamento do texto, o que ajuda na revisão, no planejamento da obra e na preparação da exportação.</p><p>Também existe a opção de <strong>exportar as estatísticas em PDF</strong>.</p></section>`,
      "exportacao-livro": `<section id="exportacao-livro"><h2>Exportação de livros</h2><p>Na tela do projeto de livro, clique em <strong>Exportar</strong>. Os formatos disponíveis são:</p><div class="table-wrap"><table><thead><tr><th>Formato</th><th>Descrição</th></tr></thead><tbody><tr><td>EPUB 2.0</td><td>Formato digital compatível com leitores e aplicativos tradicionais.</td></tr><tr><td>EPUB 3.0</td><td>Versão mais moderna do padrão EPUB.</td></tr><tr><td>XHTML</td><td>Exportação simplificada em pasta com arquivos HTML/XHTML.</td></tr><tr><td>DOCX</td><td>Documento editável, útil para revisão externa ou entrega.</td></tr><tr><td>PDF</td><td>Versão fixa para leitura, impressão ou compartilhamento.</td></tr></tbody></table></div><div class="callout warn"><strong>Observação:</strong> o formato de exportação e, no caso do EPUB, a versão escolhida afetam o arquivo final gerado, mas não alteram seu conteúdo original salvo no projeto.</div></section>`,
      "importacao-documentos": `<section id="importacao-documentos"><h2>Importação de documentos</h2><p>Além de criar capítulos e roteiros manualmente, o Gutenberg permite importar arquivos externos diretamente para um projeto existente.</p><h3>Formatos aceitos</h3><div class="table-wrap"><table><thead><tr><th>Formato</th><th>Uso no projeto</th></tr></thead><tbody><tr><td><code>.docx</code></td><td>Importa texto de documentos Word. Em livros, cria um novo capítulo; em roteiros, tenta converter o conteúdo para blocos de roteiro.</td></tr><tr><td><code>.pdf</code></td><td>Extrai linhas de texto do PDF. Em livros, organiza o conteúdo como capítulo; em roteiros, identifica cabeçalhos de cena, personagens, diálogos, transições e ações quando possível.</td></tr><tr><td><code>.txt</code></td><td>Importa texto puro. Em livros, vira capítulo; em roteiros, vira blocos classificados ou neutros quando não houver estrutura clara.</td></tr><tr><td><code>.gut</code></td><td>Importa um pacote Gutenberg salvo anteriormente, mantendo metadados e conteúdo compatível com o tipo do projeto.</td></tr></tbody></table></div><h3>Como importar em livros</h3><ol class="steps compact"><li>Abra um projeto do tipo <strong>Livro</strong>.</li><li>Clique em <strong>Importar capítulos</strong>.</li><li>Selecione um arquivo <code>.gut</code>, <code>.docx</code>, <code>.pdf</code> ou <code>.txt</code>.</li><li>Após a importação, o app abre o capítulo criado ou atualizado.</li></ol><h3>Como importar em roteiros</h3><ol class="steps compact"><li>Abra um projeto do tipo <strong>Roteiro</strong>.</li><li>Use a ação de importação disponível na tela do projeto.</li><li>Selecione um arquivo compatível.</li><li>O Gutenberg cria um roteiro e tenta preencher metadados como título, autor, logline, sinopse, gênero, contatos, personagens e locais quando esses dados aparecem no arquivo.</li></ol><div class="callout tip"><strong>Dica:</strong> em PDFs e DOCX de roteiro, linhas como <code>INT.</code>, <code>EXT.</code>, nomes centralizados em caixa alta e transições ajudam o sistema a classificar os blocos automaticamente.</div></section>`,
      "arquivos-gut": `<section id="arquivos-gut"><h2>Arquivos .gut</h2><p>O formato <strong>.gut</strong> é um snapshot próprio do Gutenberg. Ele salva conteúdo estruturado em um pacote compactado e validado, útil para backup, migração entre instalações e transporte de capítulos ou roteiros sem depender dos formatos finais de publicação.</p><h3>O que pode ser salvo</h3><ul class="clean-list"><li><strong>Livros:</strong> todos os capítulos do projeto são reunidos em um único arquivo <code>.gut</code>.</li><li><strong>Roteiros:</strong> um roteiro selecionado é salvo com seus blocos, informações, catálogo de personagens e catálogo de locais.</li></ul><h3>O que é preservado</h3><ul class="clean-list"><li>Metadados do projeto, como título, descrição, autor, idioma, tags, contatos e informações adicionais quando aplicável.</li><li>HTML estruturado do editor e texto simples de apoio.</li><li>Dados específicos de roteiro, incluindo tipo de roteiro, cabeçalho, rodapé, prefixo de cena, numeração inicial, logline, sinopse, gênero, copyright, personagens, locais e catálogos.</li><li>Data de criação e atualização dos itens exportados.</li></ul><h3>Importação pendente ao abrir arquivo</h3><p>Quando o aplicativo desktop recebe um arquivo <code>.gut</code>, a tela inicial exibe uma janela de importação pendente. Nela você pode escolher um projeto compatível ou criar um novo projeto já preenchido com os metadados disponíveis no snapshot.</p><div class="callout info"><strong>Compatibilidade:</strong> arquivos <code>.gut</code> de livro só podem ser importados em projetos de livro, e arquivos <code>.gut</code> de roteiro só podem ser importados em projetos de roteiro.</div></section>`,
      "fluxo-roteiros": `<section id="fluxo-roteiros"><h2>Fluxo de trabalho para roteiros</h2><ol class="steps"><li>Criar um novo projeto do tipo <strong>Roteiro</strong>.</li><li>Definir metadados do projeto, como contato e informações adicionais.</li><li>Criar um ou mais roteiros dentro do projeto.</li><li>Configurar tipo do roteiro, cabeçalho, rodapé, prefixo de cena e numeração inicial.</li><li>Escrever com blocos específicos de roteiro.</li><li>Usar catálogo, revisão e estatísticas.</li><li>Exportar o roteiro em DOCX ou PDF.</li></ol></section>`,
      "criar-roteiro": `<section id="criar-roteiro"><h2>Criando um projeto de roteiro</h2><p>Na tela inicial, abra <strong>Novo projeto</strong> e selecione o tipo <strong>Roteiro</strong>.</p><h3>Diferenças em relação ao projeto de livro</h3><ul class="clean-list"><li>O campo de <strong>Tags</strong> é substituído por <strong>Contato</strong>.</li><li>Há um campo de <strong>Informações adicionais</strong>.</li><li>O projeto não usa capa como item principal do fluxo.</li><li>Dentro do projeto, você cria <strong>roteiros</strong> em vez de capítulos.</li></ul><h3>Campos do roteiro interno</h3><div class="table-wrap"><table><thead><tr><th>Campo</th><th>Uso</th></tr></thead><tbody><tr><td>Nome do roteiro</td><td>Título interno do documento.</td></tr><tr><td>Cabeçalho</td><td>Texto exibido no topo do documento exportado.</td></tr><tr><td>Rodapé</td><td>Texto exibido na parte inferior do documento exportado.</td></tr><tr><td>Prefixo do número de cena</td><td>Define o prefixo da numeração das cenas.</td></tr><tr><td>Numeração de cena inicial</td><td>Ponto de partida para contagem das cenas.</td></tr><tr><td>Logline / Resumo</td><td>Descrição curta da proposta do roteiro.</td></tr><tr><td>Sinopse</td><td>Resumo mais amplo do conteúdo.</td></tr><tr><td>Gênero</td><td>Categoria geral do roteiro.</td></tr><tr><td>Tipo de roteiro</td><td>Ex.: Spec Script, Shooting Script, Revised Draft etc.</td></tr><tr><td>Copyright</td><td>Insere um aviso discreto na capa do roteiro exportado.</td></tr></tbody></table></div></section>`,
      "editor-roteiro": `<section id="editor-roteiro"><h2>Editor de roteiro</h2><p>O editor de roteiro foi desenvolvido para escrita formatada por blocos. Em vez de usar apenas parágrafos livres, você escolhe o tipo de bloco adequado ao elemento dramático que está escrevendo.</p><h3>Recursos do editor</h3><div class="card-grid two"><article class="card"><h4>Undo / Redo</h4><p>Desfazer e refazer alterações.</p></article><article class="card"><h4>Blocos específicos</h4><p>Cada trecho pode ser marcado como cena, ação, diálogo, personagem etc.</p></article><article class="card"><h4>Tema visual</h4><p>Permite alterar o modo de visualização das páginas do roteiro.</p></article><article class="card"><h4>Indicador do bloco atual</h4><p>Mostra qual tipo de bloco está ativo no cursor.</p></article><article class="card"><h4>Ocultar/mostrar comentários</h4><p>Facilita a leitura do material ao esconder comentários internos.</p></article><article class="card"><h4>Salvamento automático</h4><p>O roteiro é salvo automaticamente durante a edição.</p></article></div></section>`,
      "blocos-roteiro": `<section id="blocos-roteiro"><h2>Blocos de roteiro</h2><p>Os tipos de bloco disponíveis no editor são:</p><div class="table-wrap"><table><thead><tr><th>Bloco</th><th>Função</th><th>Atalho exibido na interface</th></tr></thead><tbody><tr><td>Cabeçalho da cena</td><td>Ex.: <code>INT. APARTAMENTO - NOITE</code></td><td>Alt + C</td></tr><tr><td>Ação</td><td>Descrição da cena e do que acontece</td><td>Alt + A</td></tr><tr><td>Personagem</td><td>Nome de quem fala</td><td>Alt + P</td></tr><tr><td>Diálogo</td><td>Fala do personagem</td><td>Alt + D</td></tr><tr><td>Parênteses</td><td>Indicação de tom, intenção ou observação curta</td><td>Alt + S</td></tr><tr><td>Plano</td><td>Descrição de enquadramento ou indicação visual</td><td>Alt + L</td></tr><tr><td>Transição</td><td>Ex.: <code>CORTE PARA</code></td><td>Alt + T</td></tr><tr><td>Comentário</td><td>Anotações internas que podem ser ocultadas</td><td>Alt + N</td></tr><tr><td>Música</td><td>Trilha, efeito ou indicação sonora</td><td>Alt + M</td></tr><tr><td>Neutro</td><td>Bloco livre para anotações gerais</td><td>Alt + E</td></tr></tbody></table></div><div class="callout info"><strong>Importante:</strong> o uso correto desses blocos melhora a consistência da formatação do roteiro, das estatísticas e da exportação.</div></section>`,
      "catalogo": `<section id="catalogo"><h2>Catálogo de personagens e locais</h2><p>O editor de roteiro possui um catálogo lateral com gerenciamento de <strong>personagens</strong> e <strong>locais</strong>. Cada item pode ter nome e descrição.</p><p>Esse catálogo serve para:</p><ul class="clean-list"><li>Centralizar referências importantes do roteiro.</li><li>Manter consistência na escrita.</li><li>Facilitar a navegação e o acompanhamento da obra.</li><li>Vincular personagens e locais a roteiros específicos pela tela do projeto.</li></ul><p>Itens podem ser criados, editados e excluídos com nome em caixa alta e descrição curta. Ao importar roteiros, o sistema também pode detectar personagens e locais automaticamente e adicioná-los ao catálogo do roteiro.</p></section>`,
      "estatisticas-roteiro": `<section id="estatisticas-roteiro"><h2>Estatísticas do roteiro</h2><p>O roteiro possui um painel próprio de estatísticas com foco em ritmo e estrutura narrativa.</p><h3>Exemplos de métricas presentes</h3><ul class="clean-list"><li>Tempo total estimado.</li><li>Total de palavras.</li><li>Total de cenas.</li><li>Quantidade de falas e blocos de diálogo.</li><li>Distribuição entre diálogo e ação.</li><li>Personagem dominante.</li><li>Cena mais longa.</li><li>Ritmo narrativo.</li><li>Locais únicos e personagens distintos.</li></ul></section>`,
      "exportacao-roteiro": `<section id="exportacao-roteiro"><h2>Exportação de roteiros</h2><p>Projetos do tipo roteiro podem exportar documentos em <strong>DOCX</strong> e <strong>PDF</strong>. Ao exportar, é necessário selecionar qual roteiro será utilizado.</p><h3>Tipos de documento disponíveis</h3><div class="table-wrap"><table><thead><tr><th>Tipo</th><th>Uso</th></tr></thead><tbody><tr><td>ROTEIRO</td><td>Documento principal formatado como roteiro.</td></tr><tr><td>OUTLINE</td><td>Estrutura resumida.</td></tr><tr><td>ESTATÍSTICA</td><td>Relatório do conteúdo.</td></tr><tr><td>COMPLETO</td><td>Versão mais abrangente, reunindo material do roteiro.</td></tr></tbody></table></div></section>`,
      "biblioteca": `<section id="biblioteca"><h2>Biblioteca EPUB e PDF</h2><p>A biblioteca é uma área separada da criação de projetos. Ela foi feita para leitura e organização de livros importados. O acesso é feito pela navegação principal, em <strong>Biblioteca</strong>.</p><h3>O que a biblioteca faz</h3><ul class="clean-list"><li>Importa arquivos <strong>.epub</strong> e <strong>.pdf</strong>.</li><li>Exibe capa quando disponível.</li><li>Organiza os livros em forma de grade.</li><li>Permite buscar por título, autor, idioma e arquivo de origem.</li><li>Filtra por <strong>Lendo</strong>, <strong>Todos</strong> e <strong>Lidos</strong>.</li><li>Cria <strong>coleções automáticas</strong> quando identifica livros relacionados.</li><li>Registra o progresso de leitura.</li><li>Permite marcar manualmente um livro como lido.</li></ul></section>`,
      "ler-epub-pdf": `<section id="ler-epub-pdf"><h2>Como ler EPUBs e PDFs</h2><h3>Adicionar livros</h3><ol class="steps compact"><li>Abra a <strong>Biblioteca</strong>.</li><li>Clique em <strong>Adicionar livro</strong>.</li><li>Selecione um ou mais arquivos EPUB ou PDF.</li><li>Aguarde o processamento.</li></ol><p>Após a importação, os itens aparecem como cards na grade. Ao clicar em um livro, o app abre o último capítulo lido ou o primeiro capítulo disponível.</p><h3>Leitura</h3><p>Durante a leitura de EPUB ou PDF, o sistema oferece:</p><ul class="clean-list"><li><strong>Sumário</strong> para navegação entre capítulos.</li><li><strong>Progresso percentual</strong> visível no topo.</li><li><strong>Tema visual</strong> da leitura.</li><li><strong>Escolha de fonte</strong>: serifada, sans-serif ou monoespaçada.</li><li><strong>Ajuste de tamanho de fonte</strong>.</li><li><strong>Botões de capítulo anterior e próximo</strong>.</li><li><strong>Memória de posição</strong>, para retomar de onde você parou.</li></ul><h3>Sobre os PDFs</h3><p>O sistema aceita arquivos PDF na biblioteca e os processa para leitura organizada dentro do aplicativo. Dependendo da estrutura do arquivo, o conteúdo pode ser apresentado em capítulos ou seções identificadas pelo sistema.</p></section>`,
      "configuracoes": `<section id="configuracoes"><h2>Configurações</h2><p>Na tela de configurações globais, você ajusta parâmetros que afetam leitura, editor e exportação.</p><h3>Configurações disponíveis</h3><div class="table-wrap"><table><thead><tr><th>Configuração</th><th>Efeito</th></tr></thead><tbody><tr><td>Recuo padrão do parágrafo</td><td>Define o recuo inicial dos parágrafos.</td></tr><tr><td>Recuo aumentado</td><td>Controla um recuo maior para usos específicos.</td></tr><tr><td>Espaço entre parágrafos</td><td>Ajusta a distância vertical entre parágrafos.</td></tr><tr><td>Espaço entre linhas</td><td>Define a altura da linha para editor e leitura.</td></tr><tr><td>Tamanho base da fonte</td><td>Controla a legibilidade padrão do texto.</td></tr><tr><td>Tamanho de H1, H2 e H3</td><td>Define a escala dos títulos.</td></tr><tr><td>Largura da área de leitura</td><td>Controla a largura do conteúdo no leitor.</td></tr><tr><td>Pasta de exportação</td><td>Diretório padrão para arquivos exportados.</td></tr><tr><td>Pasta da biblioteca</td><td>Local de armazenamento da biblioteca importada.</td></tr><tr><td>Chave da API Gemini</td><td>Necessária para o recurso de revisão.</td></tr><tr><td>Modo browser</td><td>Inicia o app apenas no navegador/tray.</td></tr><tr><td>Efeito no editor</td><td>Ativa ou desativa o efeito visual das partículas.</td></tr><tr><td>Idioma do programa</td><td>Alterna entre português e inglês na interface.</td></tr></tbody></table></div></section>`,
      "atalhos": `<section id="atalhos"><h2>Atalhos e comandos</h2><h3>Editor de livro</h3><div class="table-wrap"><table><thead><tr><th>Ação</th><th>Atalho</th></tr></thead><tbody><tr><td>Alinhar à esquerda</td><td>Alt + E</td></tr><tr><td>Centralizar</td><td>Alt + C</td></tr><tr><td>Alinhar à direita</td><td>Alt + D</td></tr><tr><td>Justificar</td><td>Alt + J</td></tr><tr><td>Negrito</td><td>Alt + B</td></tr><tr><td>Itálico</td><td>Alt + I</td></tr><tr><td>Sublinhado</td><td>Alt + U</td></tr><tr><td>Parágrafo</td><td>Alt + P</td></tr><tr><td>H1</td><td>Alt + 1</td></tr><tr><td>H2</td><td>Alt + 2</td></tr><tr><td>H3</td><td>Alt + 3</td></tr><tr><td>Lista</td><td>Alt + L</td></tr><tr><td>Linha horizontal</td><td>Alt + R</td></tr><tr><td>Separador decorativo</td><td>Ctrl + Alt + Q</td></tr><tr><td>Delimitador decorativo</td><td>Alt + Q</td></tr><tr><td>Fonte Sans</td><td>Ctrl + Alt + X</td></tr><tr><td>Fonte Serif</td><td>Ctrl + Alt + S</td></tr><tr><td>Fonte Mono</td><td>Ctrl + Alt + M</td></tr><tr><td>Inserir imagem</td><td>Ctrl + Alt + I</td></tr><tr><td>Limpar edição</td><td>Ctrl + Alt + L</td></tr><tr><td>Revisar</td><td>Ctrl + Alt + R</td></tr></tbody></table></div><h3>Editor de roteiro</h3><div class="table-wrap"><table><thead><tr><th>Ação</th><th>Atalho</th></tr></thead><tbody><tr><td>Desfazer</td><td>Ctrl + Z</td></tr><tr><td>Refazer</td><td>Ctrl + Shift + Z</td></tr><tr><td>Ocultar/mostrar comentários</td><td>Alt + O</td></tr><tr><td>Abrir catálogo de personagens</td><td>Ctrl + Alt + P</td></tr><tr><td>Abrir catálogo de locais</td><td>Ctrl + Alt + L</td></tr><tr><td>Abrir estatísticas</td><td>Ctrl + Alt + I</td></tr><tr><td>Revisão ortográfica</td><td>Ctrl + Alt + R</td></tr></tbody></table></div></section>`,
      "armazenamento": `<section id="armazenamento"><h2>Arquivos gerados e armazenamento</h2><p>O Gutenberg mantém os dados localmente. Em geral, o projeto trabalha com três grupos principais:</p><ul class="clean-list"><li><strong>Projetos</strong>: livros e roteiros criados pelo usuário.</li><li><strong>Exports</strong>: arquivos gerados na exportação.</li><li><strong>Biblioteca</strong>: livros EPUB e PDF importados para leitura.</li></ul><p>As pastas exatas podem variar conforme suas configurações, principalmente a <strong>pasta de exportação</strong> e a <strong>pasta da biblioteca</strong> definidas na tela de configurações.</p></section>`,
      "solucao-problemas": `<section id="solucao-problemas"><h2>Solução de problemas</h2><div class="faq"><article><h3>A revisão não funciona</h3><p>Verifique se a chave da API Gemini foi preenchida corretamente nas configurações.</p></article><article><h3>O projeto não exporta</h3><p>Confirme se o conteúdo existe e se a pasta de exportação está configurada corretamente.</p></article><article><h3>O PDF importado não aparece como esperado</h3><p>Alguns PDFs têm estruturas complexas. O sistema tenta organizar o conteúdo, mas o resultado pode variar conforme o arquivo original.</p></article><article><h3>O app não abre como desktop</h3><p>Confirme se as dependências do ambiente estão instaladas, incluindo as usadas pelo pywebview.</p></article><article><h3>O modo browser não inicia corretamente</h3><p>Verifique se as dependências de tray estão instaladas, como <code>pystray</code> e <code>Pillow</code>.</p></article></div></section>`,
      "boas-praticas": `<section id="boas-praticas"><h2>Boas práticas</h2><ul class="clean-list"><li>Defina o idioma correto do projeto antes de começar a revisão.</li><li>Use capítulos curtos e bem nomeados para melhorar navegação e exportação.</li><li>No roteiro, mantenha cada trecho no bloco apropriado.</li><li>Revise antes de exportar versões finais em PDF ou DOCX.</li><li>Configure corretamente a pasta da biblioteca para manter seus livros organizados.</li><li>Use o modo leitura para validar legibilidade e ritmo do texto antes da publicação.</li></ul></section>`
    }
  },
  "en-US": {
    meta: {
      title: "Gutenberg Documentation",
      brandSubtitle: "Official project documentation",
      searchPlaceholder: "Search the documentation...",
      heroEyebrow: "Documentation",
      heroTitle: "How to use Gutenberg to create books, screenplays, and read EPUBs and PDFs",
      heroDescription: `This documentation explains how the <strong>Gutenberg</strong> application works, covering project creation, chapter editing, screenplay writing, revision, export, and the integrated library used for reading.`,
      footerText: "Gutenberg project documentation.",
      menuLabel: "Open menu"
    },
    nav: [
      ["visao-geral", "Overview"], ["recursos", "Main features"], ["instalacao", "Installation and startup"], ["estrutura", "Project structure"], ["fluxo-livros", "Book workflow"], ["criar-livro", "Creating a book project"], ["editor-livro", "Book editor"], ["revisao", "Text revision"], ["estatisticas-livro", "Project statistics"], ["exportacao-livro", "Book export"], ["importacao-documentos", "Document import"], ["arquivos-gut", ".gut files"], ["fluxo-roteiros", "Screenplay workflow"], ["criar-roteiro", "Creating a screenplay project"], ["editor-roteiro", "Screenplay editor"], ["blocos-roteiro", "Screenplay blocks"], ["catalogo", "Character and location catalog"], ["estatisticas-roteiro", "Screenplay statistics"], ["exportacao-roteiro", "Screenplay export"], ["biblioteca", "EPUB and PDF library"], ["ler-epub-pdf", "How to read EPUBs and PDFs"], ["configuracoes", "Settings"], ["atalhos", "Shortcuts and commands"], ["armazenamento", "Generated files and storage"], ["solucao-problemas", "Troubleshooting"], ["boas-praticas", "Best practices"]
    ],
    sections: {
      "visao-geral": `<section class="callout info" id="visao-geral"><h2>Overview</h2><p>Gutenberg is a desktop/web application focused on <strong>creative writing</strong> and <strong>reading organization</strong>. It lets you create <strong>book</strong> and <strong>screenplay</strong> projects, edit content with automatic saving, revise text, export to formats such as EPUB, DOCX, and PDF, and keep a built-in library for reading <strong>.epub</strong> and <strong>.pdf</strong> files.</p><p>The interface was built with <strong>Flask + HTML + CSS + JavaScript</strong>, and the application can also run as a desktop program with <strong>pywebview</strong>.</p></section>`,
      "recursos": `<section id="recursos"><h2>Main features</h2><div class="card-grid two"><article class="card"><h3>Project creation</h3><p>Support for two project types: <strong>Book</strong> and <strong>Screenplay</strong>.</p></article><article class="card"><h3>Book editor</h3><p>Chapter-based editing with rich formatting, images, headings, lists, and autosave.</p></article><article class="card"><h3>Screenplay editor</h3><p>Dedicated blocks for scene, action, character, dialogue, transition, comment, music, and more.</p></article><article class="card"><h3>Text revision</h3><p>Gemini integration for spelling, grammar, punctuation, and minor writing improvements.</p></article><article class="card"><h3>Export</h3><p>Books: EPUB 2.0, EPUB 3.0, XHTML, DOCX, and PDF. Screenplays: DOCX and PDF.</p></article><article class="card"><h3>Import</h3><p>Projects can import <strong>.gut</strong>, <strong>.docx</strong>, <strong>.pdf</strong>, and <strong>.txt</strong> files, converting them into chapters or screenplays according to the project type.</p></article><article class="card"><h3>.gut snapshots</h3><p>Book chapters and screenplays can be saved as a <strong>.gut</strong> package for backup, transfer, and restoration in compatible projects.</p></article><article class="card"><h3>Library</h3><p>EPUB and PDF reading with progress tracking, chapters, table of contents, reading state, and automatic collections.</p></article></div></section>`,
      "instalacao": `<section id="instalacao"><h2>Installation and startup</h2><h3>Install dependencies</h3><pre><code>pip install -r requirements.txt</code></pre><h3>Run in the browser</h3><pre><code>python server_only.py</code></pre><p>Then open:</p><pre><code>http://127.0.0.1:5000</code></pre><h3>Run as a desktop application</h3><pre><code>python app.py</code></pre><h3>Build an executable with PyInstaller</h3><pre><code>pyinstaller Gutenberg.spec</code></pre><p>The executable will be created in <code>dist/Gutenberg/</code>.</p></section>`,
      "estrutura": `<section id="estrutura"><h2>Project structure</h2><pre><code>project_root/
├── app.py
├── server_only.py
├── modules/
├── static/
├── templates/
├── appdata/
├── locales/
├── requirements.txt
├── Gutenberg.spec
└── README.md</code></pre><div class="table-wrap"><table><thead><tr><th>Folder / file</th><th>Purpose</th></tr></thead><tbody><tr><td><code>app.py</code></td><td>Starts the desktop application with pywebview.</td></tr><tr><td><code>server_only.py</code></td><td>Runs only the Flask server.</td></tr><tr><td><code>modules/</code></td><td>Backend logic: projects, chapters, screenplays, library, export, and revision.</td></tr><tr><td><code>templates/</code></td><td>HTML pages rendered by Flask.</td></tr><tr><td><code>static/</code></td><td>CSS, JavaScript, and interface image assets.</td></tr><tr><td><code>locales/</code></td><td>Interface translations in Portuguese and English.</td></tr><tr><td><code>appdata/config.json</code></td><td>Global application settings.</td></tr><tr><td><code>appdata/progress.json</code></td><td>Local progress and state information.</td></tr></tbody></table></div></section>`,
      "fluxo-livros": `<section id="fluxo-livros"><h2>Book workflow</h2><ol class="steps"><li>Create a new project of type <strong>Book</strong>.</li><li>Set the title, description, author, language, tags, and optionally a cover.</li><li>Create chapters individually.</li><li>Edit each chapter's content in the editor.</li><li>Use text revision when needed.</li><li>Read the chapter in reading mode.</li><li>Export the project as EPUB, XHTML, DOCX, or PDF.</li></ol></section>`,
      "criar-livro": `<section id="criar-livro"><h2>Creating a book project</h2><p>On the home screen, click <strong>New project</strong>. In the creation form, select the <strong>Book</strong> type.</p><h3>Form fields</h3><div class="table-wrap"><table><thead><tr><th>Field</th><th>Description</th></tr></thead><tbody><tr><td>Title</td><td>Main project name. Required.</td></tr><tr><td>Description</td><td>Book summary or general notes.</td></tr><tr><td>Author</td><td>Author name.</td></tr><tr><td>Language</td><td>Main project language. It affects revision and identification.</td></tr><tr><td>Tags</td><td>Keywords separated by commas.</td></tr><tr><td>Cover</td><td>Optional image used in the project and export.</td></tr></tbody></table></div><div class="callout tip"><strong>Tip:</strong> use tags to organize genres, themes, or series. That makes future identification easier on the main dashboard.</div></section>`,
      "editor-livro": `<section id="editor-livro"><h2>Book editor</h2><p>Each chapter is edited on its own screen. The editor automatically saves content and lets you write with rich formatting.</p><h3>Available tools</h3><div class="card-grid two"><article class="card"><h4>Alignment</h4><p>Left, center, right, and justified alignment.</p></article><article class="card"><h4>Indentation</h4><p>Remove indentation or increase paragraph indentation.</p></article><article class="card"><h4>Style</h4><p>Bold, italic, and underline.</p></article><article class="card"><h4>Structure</h4><p>Paragraph, H1, H2, H3, and unordered list.</p></article><article class="card"><h4>Visual elements</h4><p>Horizontal line, decorative separator, and decorative delimiter.</p></article><article class="card"><h4>Extra features</h4><p>Image insertion, font family switching, and formatting cleanup.</p></article></div><h3>Autosave</h3><p>The editor uses an <strong>autosave</strong> system. That means chapter content and title are automatically sent to the backend while you work. In practice, you do not need to click a save button after every change.</p><h3>Reading mode</h3><p>Inside the editor there is a <strong>Reading mode</strong> button. It opens the chapter in a reading-focused view with options such as theme, font, font size, and reading width.</p></section>`,
      "revisao": `<section id="revisao"><h2>Text revision</h2><p>The book editor and the screenplay editor include a Gemini-based revision feature. Text is processed in blocks, preserving the original structure and proposing corrections for spelling, punctuation, agreement, and minor grammar issues.</p><h3>How to use it</h3><ol class="steps compact"><li>Open the editor.</li><li>Click the <strong>Review</strong> button.</li><li>The system prepares text blocks for analysis.</li><li>Compare the current text with the corrected suggestion.</li><li>Choose whether to ignore the block, review it again, or accept the revision.</li></ol><h3>Requirement</h3><p>For revision to work, you must set the <strong>Google Gemini API key</strong> in <strong>Settings</strong>. Without it, the feature will not be able to query the external service.</p></section>`,
      "estatisticas-livro": `<section id="estatisticas-livro"><h2>Project statistics</h2><p>Book projects include a <strong>statistics</strong> area accessible from the project screen. It was designed to track text size and behavior, which helps with revision, planning, and export preparation.</p><p>There is also an option to <strong>export the statistics as PDF</strong>.</p></section>`,
      "exportacao-livro": `<section id="exportacao-livro"><h2>Book export</h2><p>On the book project screen, click <strong>Export</strong>. The available formats are:</p><div class="table-wrap"><table><thead><tr><th>Format</th><th>Description</th></tr></thead><tbody><tr><td>EPUB 2.0</td><td>Digital format compatible with traditional readers and apps.</td></tr><tr><td>EPUB 3.0</td><td>More modern version of the EPUB standard.</td></tr><tr><td>XHTML</td><td>Simplified export as a folder with HTML/XHTML files.</td></tr><tr><td>DOCX</td><td>Editable document, useful for external review or delivery.</td></tr><tr><td>PDF</td><td>Fixed-layout version for reading, printing, or sharing.</td></tr></tbody></table></div><div class="callout warn"><strong>Note:</strong> the selected export format and, in the case of EPUB, the chosen version affect the generated final file, but do not change the original content saved in the project.</div></section>`,
      "importacao-documentos": `<section id="importacao-documentos"><h2>Document import</h2><p>In addition to creating chapters and screenplays manually, Gutenberg can import external files directly into an existing project.</p><h3>Supported formats</h3><div class="table-wrap"><table><thead><tr><th>Format</th><th>Project behavior</th></tr></thead><tbody><tr><td><code>.docx</code></td><td>Imports text from Word documents. In books, it creates a new chapter; in screenplays, it tries to convert content into screenplay blocks.</td></tr><tr><td><code>.pdf</code></td><td>Extracts text lines from the PDF. In books, it organizes the content as a chapter; in screenplays, it identifies scene headings, characters, dialogue, transitions, and action when possible.</td></tr><tr><td><code>.txt</code></td><td>Imports plain text. In books, it becomes a chapter; in screenplays, it becomes classified blocks or neutral blocks when no clear structure is found.</td></tr><tr><td><code>.gut</code></td><td>Imports a previously saved Gutenberg package, preserving metadata and content compatible with the project type.</td></tr></tbody></table></div><h3>How to import into books</h3><ol class="steps compact"><li>Open a <strong>Book</strong> project.</li><li>Click <strong>Import chapters</strong>.</li><li>Select a <code>.gut</code>, <code>.docx</code>, <code>.pdf</code>, or <code>.txt</code> file.</li><li>After import, the app opens the created or updated chapter.</li></ol><h3>How to import into screenplays</h3><ol class="steps compact"><li>Open a <strong>Screenplay</strong> project.</li><li>Use the import action available on the project screen.</li><li>Select a compatible file.</li><li>Gutenberg creates a screenplay and tries to fill metadata such as title, author, logline, synopsis, genre, contacts, characters, and locations when those details appear in the file.</li></ol><div class="callout tip"><strong>Tip:</strong> in screenplay PDFs and DOCX files, lines such as <code>INT.</code>, <code>EXT.</code>, centered uppercase names, and transitions help the system classify blocks automatically.</div></section>`,
      "arquivos-gut": `<section id="arquivos-gut"><h2>.gut files</h2><p>The <strong>.gut</strong> format is Gutenberg’s own snapshot format. It stores structured content in a compact, validated package, useful for backup, migration between installations, and moving chapters or screenplays without relying on final publishing formats.</p><h3>What can be saved</h3><ul class="clean-list"><li><strong>Books:</strong> all project chapters are bundled into a single <code>.gut</code> file.</li><li><strong>Screenplays:</strong> one selected screenplay is saved with its blocks, information, character catalog, and location catalog.</li></ul><h3>What is preserved</h3><ul class="clean-list"><li>Project metadata such as title, description, author, language, tags, contacts, and additional information when applicable.</li><li>Structured editor HTML and supporting plain text.</li><li>Screenplay-specific data, including screenplay type, header, footer, scene prefix, initial scene number, logline, synopsis, genre, copyright, characters, locations, and catalogs.</li><li>Creation and update dates for exported items.</li></ul><h3>Pending import when opening a file</h3><p>When the desktop app receives a <code>.gut</code> file, the home screen shows a pending import dialog. There you can choose a compatible project or create a new project already filled with metadata available in the snapshot.</p><div class="callout info"><strong>Compatibility:</strong> book <code>.gut</code> files can only be imported into book projects, and screenplay <code>.gut</code> files can only be imported into screenplay projects.</div></section>`,
      "fluxo-roteiros": `<section id="fluxo-roteiros"><h2>Screenplay workflow</h2><ol class="steps"><li>Create a new project of type <strong>Screenplay</strong>.</li><li>Set project metadata such as contact information and additional notes.</li><li>Create one or more screenplays inside the project.</li><li>Configure screenplay type, header, footer, scene prefix, and starting numbering.</li><li>Write using dedicated screenplay blocks.</li><li>Use the catalog, revision tools, and statistics.</li><li>Export the screenplay as DOCX or PDF.</li></ol></section>`,
      "criar-roteiro": `<section id="criar-roteiro"><h2>Creating a screenplay project</h2><p>On the home screen, open <strong>New project</strong> and select the <strong>Screenplay</strong> type.</p><h3>Differences from a book project</h3><ul class="clean-list"><li>The <strong>Tags</strong> field is replaced by <strong>Contact</strong>.</li><li>There is an <strong>Additional information</strong> field.</li><li>The project does not use a cover as a central item in the workflow.</li><li>Inside the project, you create <strong>screenplays</strong> instead of chapters.</li></ul><h3>Internal screenplay fields</h3><div class="table-wrap"><table><thead><tr><th>Field</th><th>Use</th></tr></thead><tbody><tr><td>Screenplay name</td><td>Internal document title.</td></tr><tr><td>Header</td><td>Text shown at the top of the exported document.</td></tr><tr><td>Footer</td><td>Text shown at the bottom of the exported document.</td></tr><tr><td>Scene number prefix</td><td>Defines the prefix used in scene numbering.</td></tr><tr><td>Initial scene numbering</td><td>Starting point for scene count.</td></tr><tr><td>Logline / Summary</td><td>Short description of the screenplay concept.</td></tr><tr><td>Synopsis</td><td>Broader summary of the content.</td></tr><tr><td>Genre</td><td>General category of the screenplay.</td></tr><tr><td>Screenplay type</td><td>For example: Spec Script, Shooting Script, Revised Draft, etc.</td></tr><tr><td>Copyright</td><td>Adds a discreet notice to the exported screenplay cover.</td></tr></tbody></table></div></section>`,
      "editor-roteiro": `<section id="editor-roteiro"><h2>Screenplay editor</h2><p>The screenplay editor was designed for block-based formatted writing. Instead of using only free paragraphs, you choose the block type that best matches the dramatic element you are writing.</p><h3>Editor features</h3><div class="card-grid two"><article class="card"><h4>Undo / Redo</h4><p>Undo and redo changes.</p></article><article class="card"><h4>Specific blocks</h4><p>Each excerpt can be marked as scene, action, dialogue, character, and so on.</p></article><article class="card"><h4>Visual theme</h4><p>Lets you change how screenplay pages are displayed.</p></article><article class="card"><h4>Current block indicator</h4><p>Shows which block type is active at the cursor position.</p></article><article class="card"><h4>Hide/show comments</h4><p>Makes the material easier to read by hiding internal comments.</p></article><article class="card"><h4>Autosave</h4><p>The screenplay is automatically saved while editing.</p></article></div></section>`,
      "blocos-roteiro": `<section id="blocos-roteiro"><h2>Screenplay blocks</h2><p>The block types available in the editor are:</p><div class="table-wrap"><table><thead><tr><th>Block</th><th>Purpose</th><th>Shortcut shown in the interface</th></tr></thead><tbody><tr><td>Scene heading</td><td>For example: <code>INT. APARTMENT - NIGHT</code></td><td>Alt + C</td></tr><tr><td>Action</td><td>Description of the scene and what happens</td><td>Alt + A</td></tr><tr><td>Character</td><td>Name of the speaking character</td><td>Alt + P</td></tr><tr><td>Dialogue</td><td>Character speech</td><td>Alt + D</td></tr><tr><td>Parenthetical</td><td>Tone, intention, or short note</td><td>Alt + S</td></tr><tr><td>Shot</td><td>Framing description or visual indication</td><td>Alt + L</td></tr><tr><td>Transition</td><td>For example: <code>CUT TO</code></td><td>Alt + T</td></tr><tr><td>Comment</td><td>Internal notes that can be hidden</td><td>Alt + N</td></tr><tr><td>Music</td><td>Score, effect, or sound cue</td><td>Alt + M</td></tr><tr><td>Neutral</td><td>Free block for general notes</td><td>Alt + E</td></tr></tbody></table></div><div class="callout info"><strong>Important:</strong> using these blocks correctly improves screenplay formatting consistency, statistics, and export quality.</div></section>`,
      "catalogo": `<section id="catalogo"><h2>Character and location catalog</h2><p>The screenplay editor includes a side catalog for managing <strong>characters</strong> and <strong>locations</strong>. Each item can have a name and description.</p><p>This catalog is useful to:</p><ul class="clean-list"><li>Centralize important screenplay references.</li><li>Maintain writing consistency.</li><li>Make navigation and project tracking easier.</li><li>Link characters and locations to specific screenplays from the project screen.</li></ul><p>Items can be created, edited, and deleted with uppercase names and short descriptions. When importing screenplays, the system can also detect characters and locations automatically and add them to the screenplay catalog.</p></section>`,
      "estatisticas-roteiro": `<section id="estatisticas-roteiro"><h2>Screenplay statistics</h2><p>The screenplay has its own statistics panel focused on pacing and narrative structure.</p><h3>Examples of available metrics</h3><ul class="clean-list"><li>Total estimated duration.</li><li>Total word count.</li><li>Total scene count.</li><li>Number of lines and dialogue blocks.</li><li>Distribution between dialogue and action.</li><li>Dominant character.</li><li>Longest scene.</li><li>Narrative pace.</li><li>Unique locations and distinct characters.</li></ul></section>`,
      "exportacao-roteiro": `<section id="exportacao-roteiro"><h2>Screenplay export</h2><p>Screenplay projects can export documents in <strong>DOCX</strong> and <strong>PDF</strong>. When exporting, you must select which screenplay will be used.</p><h3>Available document types</h3><div class="table-wrap"><table><thead><tr><th>Type</th><th>Use</th></tr></thead><tbody><tr><td>SCREENPLAY</td><td>Main document formatted as a screenplay.</td></tr><tr><td>OUTLINE</td><td>Condensed structure.</td></tr><tr><td>STATISTICS</td><td>Content report.</td></tr><tr><td>COMPLETE</td><td>More comprehensive version bringing together screenplay material.</td></tr></tbody></table></div></section>`,
      "biblioteca": `<section id="biblioteca"><h2>EPUB and PDF library</h2><p>The library is separate from project creation. It was designed for reading and organizing imported books. It is accessed from the main navigation under <strong>Library</strong>.</p><h3>What the library does</h3><ul class="clean-list"><li>Imports <strong>.epub</strong> and <strong>.pdf</strong> files.</li><li>Displays a cover when available.</li><li>Organizes books in a grid layout.</li><li>Lets you search by title, author, language, and source file.</li><li>Filters by <strong>Reading</strong>, <strong>All</strong>, and <strong>Read</strong>.</li><li>Creates <strong>automatic collections</strong> when related books are detected.</li><li>Tracks reading progress.</li><li>Lets you manually mark a book as read.</li></ul></section>`,
      "ler-epub-pdf": `<section id="ler-epub-pdf"><h2>How to read EPUBs and PDFs</h2><h3>Add books</h3><ol class="steps compact"><li>Open the <strong>Library</strong>.</li><li>Click <strong>Add book</strong>.</li><li>Select one or more EPUB or PDF files.</li><li>Wait for processing to finish.</li></ol><p>After import, items appear as cards in the grid. When you click a book, the app opens the last chapter you read or the first available chapter.</p><h3>Reading</h3><p>During EPUB or PDF reading, the system provides:</p><ul class="clean-list"><li><strong>Table of contents</strong> for chapter navigation.</li><li><strong>Visible percentage progress</strong> at the top.</li><li><strong>Reading theme</strong>.</li><li><strong>Font selection</strong>: serif, sans-serif, or monospace.</li><li><strong>Font size adjustment</strong>.</li><li><strong>Previous and next chapter buttons</strong>.</li><li><strong>Position memory</strong> so you can resume where you left off.</li></ul><h3>About PDFs</h3><p>The system accepts PDF files in the library and processes them for organized reading inside the application. Depending on file structure, content may be shown in chapters or sections identified by the system.</p></section>`,
      "configuracoes": `<section id="configuracoes"><h2>Settings</h2><p>On the global settings screen, you can adjust parameters that affect reading, editing, and export.</p><h3>Available settings</h3><div class="table-wrap"><table><thead><tr><th>Setting</th><th>Effect</th></tr></thead><tbody><tr><td>Default paragraph indentation</td><td>Defines the initial paragraph indentation.</td></tr><tr><td>Expanded indentation</td><td>Controls a larger indentation for specific uses.</td></tr><tr><td>Paragraph spacing</td><td>Adjusts the vertical distance between paragraphs.</td></tr><tr><td>Line spacing</td><td>Defines line height for editor and reading.</td></tr><tr><td>Base font size</td><td>Controls the default text readability.</td></tr><tr><td>H1, H2, and H3 size</td><td>Defines heading scale.</td></tr><tr><td>Reading area width</td><td>Controls content width in the reader.</td></tr><tr><td>Export folder</td><td>Default directory for exported files.</td></tr><tr><td>Library folder</td><td>Storage location for the imported library.</td></tr><tr><td>Gemini API key</td><td>Required for the revision feature.</td></tr><tr><td>Browser mode</td><td>Starts the app only in browser/tray mode.</td></tr><tr><td>Editor effect</td><td>Enables or disables the particle visual effect.</td></tr><tr><td>Program language</td><td>Switches the interface between Portuguese and English.</td></tr></tbody></table></div></section>`,
      "atalhos": `<section id="atalhos"><h2>Shortcuts and commands</h2><h3>Book editor</h3><div class="table-wrap"><table><thead><tr><th>Action</th><th>Shortcut</th></tr></thead><tbody><tr><td>Align left</td><td>Alt + E</td></tr><tr><td>Center</td><td>Alt + C</td></tr><tr><td>Align right</td><td>Alt + D</td></tr><tr><td>Justify</td><td>Alt + J</td></tr><tr><td>Bold</td><td>Alt + B</td></tr><tr><td>Italic</td><td>Alt + I</td></tr><tr><td>Underline</td><td>Alt + U</td></tr><tr><td>Paragraph</td><td>Alt + P</td></tr><tr><td>H1</td><td>Alt + 1</td></tr><tr><td>H2</td><td>Alt + 2</td></tr><tr><td>H3</td><td>Alt + 3</td></tr><tr><td>List</td><td>Alt + L</td></tr><tr><td>Horizontal line</td><td>Alt + R</td></tr><tr><td>Decorative separator</td><td>Ctrl + Alt + Q</td></tr><tr><td>Decorative delimiter</td><td>Alt + Q</td></tr><tr><td>Sans font</td><td>Ctrl + Alt + X</td></tr><tr><td>Serif font</td><td>Ctrl + Alt + S</td></tr><tr><td>Mono font</td><td>Ctrl + Alt + M</td></tr><tr><td>Insert image</td><td>Ctrl + Alt + I</td></tr><tr><td>Clear editing</td><td>Ctrl + Alt + L</td></tr><tr><td>Review</td><td>Ctrl + Alt + R</td></tr></tbody></table></div><h3>Screenplay editor</h3><div class="table-wrap"><table><thead><tr><th>Action</th><th>Shortcut</th></tr></thead><tbody><tr><td>Undo</td><td>Ctrl + Z</td></tr><tr><td>Redo</td><td>Ctrl + Shift + Z</td></tr><tr><td>Hide/show comments</td><td>Alt + O</td></tr><tr><td>Open character catalog</td><td>Ctrl + Alt + P</td></tr><tr><td>Open location catalog</td><td>Ctrl + Alt + L</td></tr><tr><td>Open statistics</td><td>Ctrl + Alt + I</td></tr><tr><td>Spelling revision</td><td>Ctrl + Alt + R</td></tr></tbody></table></div></section>`,
      "armazenamento": `<section id="armazenamento"><h2>Generated files and storage</h2><p>Gutenberg stores data locally. In general, the project works with three main groups:</p><ul class="clean-list"><li><strong>Projects</strong>: books and screenplays created by the user.</li><li><strong>Exports</strong>: files generated during export.</li><li><strong>Library</strong>: EPUB and PDF books imported for reading.</li></ul><p>The exact folders can vary depending on your settings, especially the <strong>export folder</strong> and the <strong>library folder</strong> defined on the settings screen.</p></section>`,
      "solucao-problemas": `<section id="solucao-problemas"><h2>Troubleshooting</h2><div class="faq"><article><h3>Revision does not work</h3><p>Check whether the Gemini API key was filled in correctly in settings.</p></article><article><h3>The project does not export</h3><p>Confirm that content exists and that the export folder is configured correctly.</p></article><article><h3>The imported PDF does not appear as expected</h3><p>Some PDFs have complex structures. The system tries to organize the content, but results can vary depending on the original file.</p></article><article><h3>The app does not open as a desktop application</h3><p>Confirm that environment dependencies are installed, including those used by pywebview.</p></article><article><h3>Browser mode does not start correctly</h3><p>Check whether tray dependencies are installed, such as <code>pystray</code> and <code>Pillow</code>.</p></article></div></section>`,
      "boas-praticas": `<section id="boas-praticas"><h2>Best practices</h2><ul class="clean-list"><li>Set the correct project language before starting revision.</li><li>Use short, well-named chapters to improve navigation and export quality.</li><li>In screenplays, keep each excerpt in the appropriate block.</li><li>Review before exporting final PDF or DOCX versions.</li><li>Configure the library folder correctly to keep your books organized.</li><li>Use reading mode to validate readability and pacing before publication.</li></ul></section>`
    }
  }
};

const menuToggle = document.getElementById("menuToggle");
const sidebar = document.getElementById("sidebar");
const searchInput = document.getElementById("searchInput");
const menuNav = document.getElementById("menuNav");
const sectionsContainer = document.getElementById("sectionsContainer");
const langPt = document.getElementById("langPt");
const langEn = document.getElementById("langEn");
const hero = document.querySelector(".hero");
const footer = document.querySelector(".footer");
const LOCALE_KEY = "gutenberg-doc-locale";
const LOCALE_INIT_KEY = "gutenberg-doc-locale-initialized-v2";

/** Getinitiallocale. Usada pelo fluxo principal da aplicação. */
function getInitialLocale() {
  const savedLocale = localStorage.getItem(LOCALE_KEY);
  const wasInitialized = localStorage.getItem(LOCALE_INIT_KEY);

  if (!wasInitialized) {
    localStorage.setItem(LOCALE_KEY, "en-US");
    localStorage.setItem(LOCALE_INIT_KEY, "1");
    return "en-US";
  }

  return savedLocale === "pt-BR" || savedLocale === "en-US" ? savedLocale : "en-US";
}

let currentLocale = getInitialLocale();
let observer = null;

/** Setlocale. Usada pelo fluxo principal da aplicação. */
function setLocale(locale) {
  if (locale === currentLocale) return;
  currentLocale = locale;
  localStorage.setItem("gutenberg-doc-locale", locale);
  document.body.classList.add("locale-switching");
  window.setTimeout(() => {
    ensureContentShells();
renderLocale();
    window.requestAnimationFrame(() => {
      window.setTimeout(() => document.body.classList.remove("locale-switching"), 60);
    });
  }, 180);
}

/** Ensurecontentshells. Usada pelo fluxo principal da aplicação. */
function ensureContentShells() {
  [hero, sectionsContainer, footer].forEach((element) => {
    if (element) element.classList.add("content-shell");
  });
}

/** Renderlocale. Usada pelo fluxo principal da aplicação. */
function renderLocale() {
  const t = translations[currentLocale];
  document.documentElement.lang = currentLocale;
  document.title = t.meta.title;
  document.getElementById("brandSubtitle").textContent = t.meta.brandSubtitle;
  searchInput.placeholder = t.meta.searchPlaceholder;
  document.getElementById("heroEyebrow").textContent = t.meta.heroEyebrow;
  document.getElementById("heroTitle").textContent = t.meta.heroTitle;
  document.getElementById("heroDescription").innerHTML = t.meta.heroDescription;
  document.getElementById("footerText").textContent = t.meta.footerText;
  menuToggle.setAttribute("aria-label", t.meta.menuLabel);
  langPt.classList.toggle("active", currentLocale === "pt-BR");
  langEn.classList.toggle("active", currentLocale === "en-US");
  document.querySelector(".lang-switch").classList.toggle("is-en", currentLocale === "en-US");
  menuNav.innerHTML = t.nav.map(([id, label]) => `<a href="#${id}">${label}</a>`).join("");
  sectionsContainer.innerHTML = t.nav.map(([id]) => t.sections[id]).join("");
  bindNavigation();
  setupObserver();
  applySearch();
}

/** Bindnavigation. Usada pelo fluxo principal da aplicação. */
function bindNavigation() {
  const navLinks = [...document.querySelectorAll("#menuNav a")];
  navLinks.forEach(link => {
    link.addEventListener("click", () => {
      if (window.innerWidth <= 1024) sidebar.classList.remove("open");
    });
  });
}

/** Setupobserver. Usada pelo fluxo principal da aplicação. */
function setupObserver() {
  const sections = [...document.querySelectorAll("main section")];
  const navLinks = [...document.querySelectorAll("#menuNav a")];
  if (observer) observer.disconnect();
  observer = new IntersectionObserver((entries) => {
    entries.forEach(entry => {
      if (!entry.isIntersecting) return;
      const id = entry.target.id;
      navLinks.forEach(link => {
        link.classList.toggle("active", link.getAttribute("href") === `#${id}`);
      });
    });
  }, { rootMargin: "-25% 0px -60% 0px", threshold: 0.1 });
  sections.forEach(section => observer.observe(section));
}

/** Clearsearchstate. Usada pelo fluxo principal da aplicação. */
function clearSearchState() {
  const sections = [...document.querySelectorAll("main section")];
  sections.forEach(section => {
    section.classList.remove("hidden-by-search");
    section.classList.remove("highlight");
  });
}

/** Applysearch. Usada pelo fluxo principal da aplicação. */
function applySearch() {
  const term = searchInput.value.trim().toLowerCase();
  const sections = [...document.querySelectorAll("main section")];
  clearSearchState();
  if (!term) return;
  sections.forEach(section => {
    const text = section.innerText.toLowerCase();
    const match = text.includes(term);
    section.classList.toggle("hidden-by-search", !match);
    section.classList.toggle("highlight", match);
  });
}

menuToggle.addEventListener("click", () => sidebar.classList.toggle("open"));
searchInput.addEventListener("input", applySearch);
langPt.addEventListener("click", () => setLocale("pt-BR"));
langEn.addEventListener("click", () => setLocale("en-US"));

document.addEventListener("click", (event) => {
  if (window.innerWidth > 1024) return;
  if (!sidebar.classList.contains("open")) return;
  const clickedInsideSidebar = sidebar.contains(event.target);
  const clickedToggle = menuToggle.contains(event.target);
  if (!clickedInsideSidebar && !clickedToggle) sidebar.classList.remove("open");
});

ensureContentShells();
renderLocale();
